name: Docker Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3
      - name: Build Docker image
        run: |
          docker build -t event_horizon .
